@startuml development_procedure
!theme blueprint
skinparam defaultFontName Arial

<style>
activityDiagram {
    diamond {
        BackgroundColor #6666cc
        FontSize 15
    }
}
</style>

start
note right: Start
    :The stage version running OK and passing tests;
    :There are enough new features to deploy a new release?;
    :Make a new release in GitHub;
    group GitHub pipeline
        :CD pipeline is triggered;
        :GitHub Actions send source code to AWS CodePipeline;
    end group
    group AWS pipeline
        :AWS pipeline is triggered;
        :Docker build and deploy image to Elastic Container Registry (ECR);
        :CodeDeploy deploys the image to ECS running on a EC2 instance;
    end group
    group Final check
        while(Is the app working correctly?) is (No)
            :Check logs, quick debug;
            if(Is the error fixed?) then (No)
                :Rollback;
                end
                note right: End
            else (Yes)

            endif
        endwhile(Yes)        
        end
        note right: End


title Pizza-Planet CD procedure
@enduml